### ISSUE TITLE
Need icons defined for gnome-calendar and gnome-books

### ISSUE THREAD

**Issue by crouthamela** [numixproject/numix-icon-theme-square#11]
One of the few "default" applications that do not appear to have a square icon defined is gnome-calendar and gnome-books. Gnome-books could use the Calibre icon, or Calibre-Viewer. I'm not sure on gnome-calendar. Gnome Help also needs one, but I was unable to identify the executable called when launching that.

**Comment by palob** [comment]
Hi, this will improve (slowly). Please cf. https://github.com/numixproject/numix-core/issues/3481.
