### ISSUE TITLE
Icon for Mail Reader in Xfce4.13 is a circle.

### ISSUE THREAD

**Issue by JotaRandom** [numixproject/numix-icon-theme-square#12]
Resents versions of the Soon™ Xfce 4.14 in this square theme is a circle.
![captura de pantalla_2017-08-22_04-04-44](https://user-images.githubusercontent.com/855726/29552783-aea2a972-86e6-11e7-8a4f-30eaa7d7bf64.png)
Aparently they change the icon "name" thing because the old was not compliant with fd.o

Xfconf 4.12.1-2
Garcon 0.6.1-1
exo 0.11.5-1
xfce4-panel 4.12.1-1

**Comment by Foggalong** [comment]
Could you report this issue [here](https://github.com/numixproject/numix-core)? I think it might be a problem for both Circle & Square (that doesn't look like one of our icons) rather than the Square packaging specifically

**Comment by palob** [comment]
This looks like they chose an emblem icon, so we probably can't fix it.
Please find out the icon name, @jristz and attach it to your new report.

**Comment by JotaRandom** [comment]
A few icon changes too
https://git.xfce.org/xfce/exo/commit/?id=fd3a75ff5bf2ec4c20b8bd114d5a70ac911f95b2
https://git.xfce.org/xfce/exo/commit/?id=199534217cfc30c342ea6d881ffebf72ad9d45b0
https://git.xfce.org/xfce/exo/commit/?id=24a27170604dba7c9e518ce6d0884bb0b5fe819b
And here the culprit https://git.xfce.org/xfce/exo/commit/?id=29474fe37267266e785511808ff2586bd196600c

**Comment by Foggalong** [comment]
Yeah @jristz we can't do anything about this. You'll need to tell them on that issue that even though they're now using a freedesktop standard icon they're using it in entirely the wrong context which will play havoc with icon themes.

**Comment by JotaRandom** [comment]
I send a mail to the xfce-dev mailist and I will see what they say,
depending on that i will open a bug but I think the problem relly on the
need of a stadard icon to use.

*Pablo Lezaeta*

Edit: more icon changes https://git.xfce.org/xfce/xfce4-panel/commit/?id=d768b1a6ff8ab285a9993180638b356e9bd694f5

**Comment by Foggalong** [comment]
If there doesn't exist a standard icon for an email app the solution isn't to use an emblem icon. They're designed to be used in an entirely different context so it's going to cause a mess with every icon theme which supports emblems.

Feel free to link them to this thread / me if they need more information.

**Comment by palob** [comment]
We've got ``mail_generic`` and ``mail-generic``. IIRC Pantheon Mail use(s/d) one of these.

**Comment by JotaRandom** [comment]
At the end this was the triggering bug
https://bugzilla.xfce.org/show_bug.cgi?id=13711

and I the mail thread is here
https://mail.xfce.org/pipermail/xfce4-dev/2017-August/031992.html

I mailed the xdg mailist but it seem avandoned.
