### ISSUE TITLE
system-logout and system-shutdown icons

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-icon-theme-square#13]
Could these be made square to match all the app icons? I realise these two are in the main Numix icon theme, but they look inconsistent in Linux Mint, especially since the lock screen icon is square.

**Comment by bilelmoussaoui** [comment]
Hey, Thanks for the issue and the bounty on BountySource. 
The issue must be reported to [numix-core ](https://github.com/numixproject/numix-core). This repository is just a packaging one. 

If you can provide the icon names that would be really helpful too or some screenshots of where you see those icons 
Thanks
