### ISSUE TITLE
icon disappears in kde

### ISSUE THREAD

**Issue by YuriFontella** [numixproject/numix-icon-theme-square#16]
starts with the icons ... but after changing the volume it disappears and stays the same with the question mark.

Desktop: KDE Plasma 5.11

https://imgur.com/Qbv1GNV

**Comment by Foggalong** [comment]
Congratulations on being one of the very few people to report an issue that's actually a problem with the Linux packaging rather than just an icon request! So at first boot the icons appear and then they disappear?

**Comment by YuriFontella** [comment]
The package is complete, thanks for that.

Let's say the system starts with the volume at 100% (the icon will be there). When you change the volume to 50% and then the icon disappears (question mark).

Strange that when I use the Numix package this does not happen, only with Numix Square.

**Comment by Foggalong** [comment]
Huh, that is really strange. Do you have the same problem with Numix Circle?

**Comment by YuriFontella** [comment]
This same problem happens.

But it is not affecting me at all.
I keep using it quietly.

Even because it may be some bug of the kde plasma itself.

**Comment by palob** [comment]
@YuriFontella What does the ``Inherits=`` line of the ``index.theme`` of your Numix installation look like?

**Comment by YuriFontella** [comment]
I think everything is alright https://i.imgur.com/nhZ3nD0.jpg

**Comment by palob** [comment]
Can you please post a screenshot of ``Numix``, i.e. not ``Numix-Light``?

**Comment by YuriFontella** [comment]
These are the Numix icons that I have available ... I use the light because my panel is light

https://imgur.com/a/14ioe

**Comment by palob** [comment]
How does it look after adding ``Breeze`` or ``breeze`` to the inherits?

**Comment by YuriFontella** [comment]
still the same thing

**Comment by palob** [comment]
Hmm, how is it supposed to look like? Can you please show a screenshot with breeze applied?

**Comment by YuriFontella** [comment]
It would be nice if someone tested on another machine.

I use Arch Linux with KDE.

**Comment by Foggalong** [comment]
Couldn't reproduce this issue unfortunately :disappointed:
