### ISSUE TITLE
Numix square does not work for some programs and icons

### ISSUE THREAD

**Issue by rbieb** [numixproject/numix-icon-theme-square#18]
Fedora 23 with cinnamon.

Programs like nemo do not change their icons at all after setting Numix square as theme. It still uses the icons in /usr/share/icons/Adwaita.

Other programs work just fine. Cinnamon settings for example.

**Comment by bjaanes** [comment]
Has anyone found a solution for this?

**Comment by Foggalong** [comment]
There's a big change coming for square to be announce over the next week or so :) watch this space (or repo rather)!

**Comment by rbieb** [comment]
Update: It was the missing numix-icon-theme.

I initially thought that numix-icon-theme-square was sufficient, but numix-icon-theme is definitely needed.

This issue can be closeq.
