### ISSUE TITLE
Square in the PPA

### ISSUE THREAD

**Issue by Foggalong** [numixproject/numix-icon-theme-square#2]
Now we're releasing Square, it needs including in our repos :grinning: 

PPA: `ppa:numix/ppa`
Package Name: `numix-icon-theme-circle`

**Comment by khurshid-alam** [comment]
Icon theme is now available in the PPA

```
sudo add-apt-repository ppa:numix/ppa
sudo apt-get update
sudo apt-get install numix-icon-theme-square
```
