### ISSUE TITLE
Add few screenshots

### ISSUE THREAD

**Issue by bilelmoussaoui** [numixproject/numix-icon-theme-square#20]
The README looks so empty without a screenshot of the few icons of the icon theme. 
The same goes for Circle and the base theme. Those screenshots could be used later on the flatpak package (which will be shown on the software center)

**Comment by mymindstorm** [comment]
Here are a few from a fresh install of Fedora

![screenshot from 2018-01-29 22-02-44](https://user-images.githubusercontent.com/27789806/35548117-fc605166-0542-11e8-8dd4-a588753bb0f8.png)
![screenshot from 2018-01-29 22-15-35](https://user-images.githubusercontent.com/27789806/35548118-fc73865a-0542-11e8-8a0a-f666676f2820.png)
![screenshot from 2018-01-29 22-19-18](https://user-images.githubusercontent.com/27789806/35548119-fc8648f8-0542-11e8-9df8-5832a1bef890.png)

**Comment by mymindstorm** [comment]
Circle:
![screenshot from 2018-01-29 22-16-46](https://user-images.githubusercontent.com/27789806/35548149-30083d94-0543-11e8-8fb3-121c98bd7aa7.png)
![screenshot from 2018-01-29 22-16-59](https://user-images.githubusercontent.com/27789806/35548150-3019d536-0543-11e8-818e-a2fa73a4d6d0.png)
![screenshot from 2018-01-29 22-17-33](https://user-images.githubusercontent.com/27789806/35548151-302c7a74-0543-11e8-8b21-8f47fe9d914e.png)

**Comment by Foggalong** [comment]
Fixed in master, thanks @mymindstorm for providing the screenshots :+1:
