### ISSUE TITLE
Icon for mattermost is missing

### ISSUE THREAD

**Issue by mholecy** [numixproject/numix-icon-theme-square#25]
A numix-square icon for mattermost application is missing.
Icon line says "mattermost-desktop" and original icon is attached.
![screenshot from 2018-02-06 16-43-30](https://user-images.githubusercontent.com/6795825/35868604-46820f12-0b5d-11e8-9629-598d2d13e857.png)

**Comment by Foggalong** [comment]
Please read the readme
