### ISSUE TITLE
Similar Icons

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-icon-theme-square#26]
![Indistinguishable Icons](https://user-images.githubusercontent.com/23306695/37449032-ca5f1236-284e-11e8-99c1-4cf735e6fdda.png)

Indistinguishable icons between GNOME characters and GNOME Fonts.

**Comment by palob** [comment]
Hi, can you please reopen this here https://github.com/numixproject/numix-core and report the missing icon for *Firefox Quantum* as well?

**Comment by ghost** [comment]
Hey!
Yeah, sure. I did it ![here](https://github.com/numixproject/numix-core/issues/4296)
Firefox Quantum is fine. That's custom compiled Quantum.
