### ISSUE TITLE
GNOME 3.28 change of iconnamings

### ISSUE THREAD

**Issue by killajoe** [numixproject/numix-icon-theme-square#27]
Related to update to GNOME 3.28 GNOME changes some iconnames, this causes that p.x. gnome-music shows a standard icon instead of the numix one.
from 
`Icon=org.gnome.Music` (from desktop file)
may create a symlink to link `gnome-music.svg` with
`org.gnome.Music.svg`

**Comment by palob** [comment]
Already being taken care of https://github.com/numixproject/numix-core/pull/4304
