### ISSUE TITLE
Three missed icons of CrossFTP, IGdm and Mozc Setup, and the Insync Help doesn't display the icon

### ISSUE THREAD

**Issue by gusbemacbe** [numixproject/numix-icon-theme-square#28]
Hello,

I drew an icon for Mozc Setup. I have just pulled a request: https://github.com/numixproject/numix-icon-theme-square/pull/29.

And other two missed icons:
— [CrossFTP](http://www.crossftp.com/)
— [IGdm](http://igdm.me/)

Although Insync has already an icon, but there is another app desktop generated by Insync called Insync Help which doesn't display correctly the same icon of Insync.

**Comment by palob** [comment]
Hi, please open icon issues and pull requests against this repo: https://github.com/numixproject/numix-core
