### ISSUE TITLE
Square in Corp

### ISSUE THREAD

**Issue by Foggalong** [numixproject/numix-icon-theme-square#3]
Now we're releasing Square, it needs including in our repos :grinning: 

Repo: `numix/numix`
Package Name: `numix-icon-theme-circle`

**Comment by bilelmoussaoui** [comment]
@Foggalong As we already have the circle icon theme in the official repos of Fedora. We should try to get the square one too.

**Comment by mymindstorm** [comment]
@bil-elmoussaoui I was looking into learning how to make a rpm spec file and submitting it if that's ok with you and @Foggalong. Also, it looks like the maintainer of the other numix-* fedora packages stopped updating the packages roughly 8 months ago (see: [Bohdi](https://bodhi.fedoraproject.org/users/sspreitz) and [one of a few bugs](https://bugzilla.redhat.com/show_bug.cgi?id=1501574)). I'm not really sure what anyone can do about that though.

**Comment by mymindstorm** [comment]
Made a .spec file and [put a review request in their system](https://bugzilla.redhat.com/show_bug.cgi?id=1530084)

**Comment by mymindstorm** [comment]
CC: @sspreitzer didn't notice you had a github handle. I'm willing to co-maintain numix-* packages if you don't have the time to update them anymore.

**Comment by mymindstorm** [comment]
It's been about a month and I haven't gotten a sponsor on the Fedora package, so I made a copr package that I'll update for the time being at `mymindstorm/numix`.

I made a pr to update the readme at #22

**Comment by mymindstorm** [comment]
9 months later and I finally have a sponsor! Except a PR sometime soon, after the package finishes getting setup.
