### ISSUE TITLE
Missing numix-icon-theme-square in ppa for Ubuntu 18.04

### ISSUE THREAD

**Issue by danleepw** [numixproject/numix-icon-theme-square#30]
Will square icon be added into the ppa?

**Comment by jgandert** [comment]
It also seems to be missing from the official 18.04 repositories

https://packages.ubuntu.com/search?keywords=numix&searchon=all&suite=bionic&section=all

At least the README seems to indicate that it should be there:

> If you use Debian, Ubuntu, or any of their derivatives then you're sorted! Numix Square is available from the official repositories. Fedora packaging is not in Fedora's offical repository yet, but we do have a copr repository you can get Numix Square from.

**Comment by Foggalong** [comment]
@khurshid-alam?

**Comment by khurshid-alam** [comment]
@Foggalong 

Already converted most of the numix gtk/icon themes....But for bzr packaging repos, it seems all the branches/tags can't be kept...it is skipping few ! (a bug in bzr dpush). Packaging repos only has 3/4 commits with maximum 4 branches (bzr) but I still want them all. It needs to be done properly. Will be fixed soon.

**Comment by khurshid-alam** [comment]
Fixed.

**Comment by jgandert** [comment]
Will it also be added to the official (Ubuntu) 18.04 repositories?

**Comment by palob** [comment]
No, alas Ubuntu isn't a rolling release distro. So unless something changed repos won't be altered after release.

**Comment by danleepw** [comment]
@khurshid-alam , that works nice. Thanks a lot.
