### ISSUE TITLE
KDE Plasma OSD icons

### ISSUE THREAD

**Issue by boussou** [numixproject/numix-icon-theme-square#33]
There are new icons on Plasma last version for OSD when you hit fn+display (I think it is since january 2018). Once installed they are located here /usr/share/icons/breeze/applets/64 and they are named like osd*

See how it looks with breeze:
![screenshot_20180813_131630](https://user-images.githubusercontent.com/2531688/44028756-3fc6d14e-9efb-11e8-9ac9-a23ee3103f66.png)

I am a big fan of Numix-Square, so I did not want to switch back to breeze just for that.

Here is how I fixed it:

in /usr/share/icons/Numix-Square/index.theme
I just added: 

`Inherits=Numix,breeze`
instead of 
`Inherits=Numix`

**Comment by Foggalong** [comment]
This is the wrong repo! You need to ask in numix-icon-theme
