### ISSUE TITLE
Add Postman icon

### ISSUE THREAD

**Issue by GiovanniCardamone** [numixproject/numix-icon-theme-square#39]
Would be nice if i can have postman icon for this pack:

Postman: https://www.postman.com/

**Comment by palob** [comment]
Hi, can you please reopen your request here https://github.com/numixproject/numix-core and add the icon name from the respective ``.desktop`` launcher file? Tutorial can be found in the README there.

We've already got a postman icon, so this might be a matter of a symlink.
