### ISSUE TITLE
Square in AUR

### ISSUE THREAD

**Issue by Foggalong** [numixproject/numix-icon-theme-square#4]
Now we're releasing Square, it needs including in our repos :grinning:

Repo: ???
Package Name: numix-icon-theme-square

**Comment by Foggalong** [comment]
Thinking about it, I don't actually know if the AUR package for Circle is official community maintained. Does anyone know?

**Comment by lots0logs** [comment]
@Foggalong Is there a package already in the AUR? If not I can maintain it since I already maintain one for Antergos.

**Comment by bilelmoussaoui** [comment]
Done https://aur.archlinux.org/packages/numix-square-icon-theme-git/

**Comment by Foggalong** [comment]
@lots0logs There's [this package](https://aur.archlinux.org/packages/numix-icon-theme-square/) which I believe was at one point hosting a pirated copy of the theme. I'd forgot that Antergos would already be maintaining an Arch package for it!

I'm not so clued up on Arch packaging so the discussion about how to set up consistent system might be best left to you, @bilelmoussaoui, and @alucryd.

**Comment by bilelmoussaoui** [comment]
@alucryd I can add you as a co-maintainer of the Square repo if you wish to. I can keep maintaining in case you don't have enough time:)

**Comment by alucryd** [comment]
@bil-elmoussaoui : Nah it's fine, the package is all yours to maintain :)

**Comment by Foggalong** [comment]
Awesome, so is this one fixed now?

**Comment by bilelmoussaoui** [comment]
yeah i'm using it right now :)
