### ISSUE TITLE
Bug with last package update

### ISSUE THREAD

**Issue by willbelr** [numixproject/numix-icon-theme-square#6]
[2016-11-15 10:06] [ALPM] upgraded numix-icon-theme-square (1:0.r83.3bc6d001-1 -> 1:0.r83_6-1)

After this update, the icons in obmenu-generator no longer work. Before it was possible to use the app name in order to get the corresponding icon (ie. 'thunar'), and now the full path to icon must be entered '/usr/share/icons/ ... /thunar.svg'. Icons path are broken in both the custom and automatic entries (generated from application categories)

I use antergos linux with lasted kernel, system is up to date, DE is custom (openbox + mostly components of lxde, xfce). I noticed the bug after updating my laptop and then confirmed the same behavior on my pc.

**Comment by lots0logs** [comment]
@Foggalong This must be related to #5 I'll check on the package to make sure everything is okay asap.

**Comment by willbelr** [comment]
The bug was a missing symlink:
/usr/share/icons/Numix-Square/48x48 to /usr/share/icons/Numix-Square/48

Works fine now :)

**Comment by Foggalong** [comment]
Oh jees. That sounds like the obmenu has hardcoded that icon themes should use `/sizexsize` rather than just `/size` when making a theme which is definitely an issue on their part. Do you have this issue with any other icon themes?

**Comment by willbelr** [comment]
Gnome, Adwaita and HighContrast all work, but they use the sizexsize scheme. obmenu-generator has a config.pl file which point to the theme directory, but did not work for me. As default the locations are set to:

```
                         desktop_files_paths     => ["/usr/share/applications", "/usr/local/share/applications"],
                         gtk_rc_filename         => "/home/will/.gtkrc-2.0",
                         icon_dirs_first         => undef,
                         icon_dirs_last          => undef,
                         icon_dirs_second        => undef,
```

So the theme informations are loaded from the gtkrc file:

include "/home/will/.gtkrc-2.0.mine"
gtk-theme-name="Numix-Frost"
gtk-icon-theme-name="Numix-Square"
gtk-font-name="Sans 10"
gtk-cursor-theme-name="Adwaita"
gtk-cursor-theme-size=0
gtk-toolbar-style=GTK_TOOLBAR_ICONS
gtk-toolbar-icon-size=GTK_ICON_SIZE_SMALL_TOOLBAR
gtk-button-images=1
gtk-menu-images=1
gtk-enable-event-sounds=0
gtk-enable-input-feedback-sounds=0
gtk-xft-antialias=1
gtk-xft-hinting=1
gtk-xft-hintstyle="hintfull"
gtk-xft-rgba="rgb"

**Comment by Foggalong** [comment]
This looks to be an issue with obmenu, not with Numix specifically.
