### ISSUE TITLE
Some icon's edge shows the inferior layer color instead of superior one

### ISSUE THREAD

**Issue by hlechner** [numixproject/numix-icon-theme-square#7]
Hello Numix team
Nice to see the square theme in github too!

I've noticed apparently a bug in the square ones:

I didn't noticed it in my full-hd 15" of my laptop but it comes obviously in my full-hd 23": 
![image](https://cloud.githubusercontent.com/assets/11244067/21546282/f7989a46-cdc4-11e6-96da-b068aee10c59.png)
![image](https://cloud.githubusercontent.com/assets/11244067/21546301/10eb6622-cdc5-11e6-9125-d6809868e9c3.png)

In the corner of some square icons, it's possible to notice the superior layer not completely over the inferior one, so it possible to see the color of the inferior layer.

The two examples above it's possible to check a white "line" on the edge (right, superior)

It does happen with this too:
![image](https://cloud.githubusercontent.com/assets/11244067/21546590/e26f7304-cdc6-11e6-8675-2bded4bf4404.png)

However due to the colors of the design is hard to notice on this one.

**Comment by hlechner** [comment]
![image](https://cloud.githubusercontent.com/assets/11244067/21546743/3c5fdd12-cdc8-11e6-9139-3c20bc7c3544.png)

**Comment by palob** [comment]
Alright, I know what causes this. It's one for https://github.com/numixproject/numix-core/issues/3482.

**Comment by Foggalong** [comment]
The issue tracker here is just for the packaging side of things, so the issue will be dealt with at the link above :)
