### ISSUE TITLE
Icons Request

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-icon-theme-square#8]
these icons already are in numix-circle

Icon=enpass

Icon=wire

Icon=org.gnome.Calendar

Icon=etcher

Icon=gnome-appfolders-manager

Icon=gtk3-demo

Icon=hp_logo

Icon=rapid-photo-downloader

Icon=org.gnome.Books

Thx

**Comment by palob** [comment]
Hi, Numix Square will get all our Circle icons, see https://github.com/numixproject/numix-core/issues/3481.
