### ISSUE TITLE
Visual Studio Code Icon Workaround does not work for Square theme

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-icon-theme-square#9]
I am aware of the plethora of duplicate issues for missing Visual Studio Code icons and the reasons for the issue therein.

When using Numix Circle icon theme, the workaround to change the .desktop launcher file icon to read `Icon=vscode` does work as intended.

However, this functionality is not mirrored by the Numix Square icon theme. In the big list of icons in issue https://github.com/numixproject/numix-core/issues/3481 there is an entry for "vstudio" (that is checked) and "visualstudiocode" (that is not checked). I did attempt to use `Icon=vstudio` instead of `Icon=vscode` but did not have any luck.

Any idea on a similar workaround for Numix Square?

**Comment by palob** [comment]
To be adressed here https://github.com/numixproject/numix-core/issues/3481.
